# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_video_player(object):
    def setupUi(self, video_player):
        video_player.setObjectName("video_player")
        video_player.resize(1528, 1005)
        self.centralwidget = QtWidgets.QWidget(video_player)
        self.centralwidget.setObjectName("centralwidget")
        self.injection_status = QtWidgets.QLabel(self.centralwidget)
        self.injection_status.setGeometry(QtCore.QRect(650, 660, 31, 31))
        self.injection_status.setText("")
        self.injection_status.setAlignment(QtCore.Qt.AlignCenter)
        self.injection_status.setObjectName("injection_status")
        self.cam_viewer = QtWidgets.QFrame(self.centralwidget)
        self.cam_viewer.setGeometry(QtCore.QRect(1259, 99, 251, 881))
        self.cam_viewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cam_viewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cam_viewer.setObjectName("cam_viewer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cam_viewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.connection_viewer = QtWidgets.QFrame(self.centralwidget)
        self.connection_viewer.setGeometry(QtCore.QRect(1259, 19, 251, 71))
        self.connection_viewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connection_viewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connection_viewer.setObjectName("connection_viewer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.connection_viewer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.host_label_2 = QtWidgets.QLabel(self.connection_viewer)
        self.host_label_2.setObjectName("host_label_2")
        self.gridLayout_3.addWidget(self.host_label_2, 0, 0, 1, 1)
        self.host_label = QtWidgets.QLabel(self.connection_viewer)
        self.host_label.setObjectName("host_label")
        self.gridLayout_3.addWidget(self.host_label, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.connection_viewer)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.ssh_status_label = QtWidgets.QLabel(self.connection_viewer)
        self.ssh_status_label.setObjectName("ssh_status_label")
        self.gridLayout_3.addWidget(self.ssh_status_label, 1, 1, 1, 1)
        self.video_widget = VideoWidget(self.centralwidget)
        self.video_widget.setGeometry(QtCore.QRect(10, 20, 1231, 961))
        self.video_widget.setObjectName("video_widget")
        video_player.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(video_player)
        self.statusbar.setObjectName("statusbar")
        video_player.setStatusBar(self.statusbar)

        self.retranslateUi(video_player)
        QtCore.QMetaObject.connectSlotsByName(video_player)

    def retranslateUi(self, video_player):
        _translate = QtCore.QCoreApplication.translate
        video_player.setWindowTitle(_translate("video_player", "InjectionController"))
        self.host_label_2.setText(_translate("video_player", "SSH Host:"))
        self.host_label.setText(_translate("video_player", "N/A"))
        self.label.setText(_translate("video_player", "Status:"))
        self.ssh_status_label.setText(_translate("video_player", "Failed"))
from qfluentwidgets.multimedia import VideoWidget
