jira_type: 1j5
use_confluence: 'True'
source_template:
- /home/zhangliwei01/ZONE/TestProject/ES39/zpd_es39_20250120_010000/04_TestData/1-Obstacles/03_OutputResult/bugItems/bug_summary.csv
goal: 1
config_list_1j5:
- sw_version
- test_object
- scenario_type
- topic
- bug_type
config_list_2j5:
- sw_version
- test_object
- scenario_id
- bug_type
assignee_template:
  /VA/Obstacles: liujianwei02
  /VA/BevObstaclesDet: wangtong02
  /VA/BackViewObstacles2dDet: lisen04
  /VA/FrontWideObstacles2dDet: lisen04
  /VA/BevLines: lixiyue01
  2j5: buyujun
  default: lisen04
bug_template:
  1j5:
    issuetype:
      id: '10403'
    customfield_11568:
    - value: 感知
    customfield_11425:
    - value: SMSC-AC
    customfield_11567:
    - value: 其他
    customfield_11008:
      value: 性能
    customfield_10689:
      value: 低(<20%)
    versions:
    - name: daily08/01
    customfield_10684:
      value: B
    customfield_10200:
    - value: IPD平台
    customfield_10687:
      value: 软件合格性测试
    priority:
      name: Medium
    labels: []
    project:
      id: 10948
    summary: zpd_es39_20250107_010621-动态障碍物-夜晚&晴天&高速,快速路-/VA/BackViewObstacles2dDet-负样本漏检测
    description: '测试版本: ES39, zpd_es39_20250107_010621<br/>测试时间: 2025-01-07 11:27:11<br/>异常类型:
      负样本漏检测<br/>异常发生时刻的场景和截图见附件<br/>-------------'
    assignee:
      name: lisen04
  2j5:
    issuetype:
      id: '10403'
    customfield_11568:
    - value: 感知
    customfield_11425:
    - value: SMSC-AC
    customfield_11567:
    - value: 其他
    customfield_11008:
      value: 性能
    customfield_10689:
      value: 低(<20%)
    versions:
    - name: daily08/01
    customfield_10684:
      value: B
    customfield_10200:
    - value: IPD平台
    customfield_10687:
      value: 软件合格性测试
    priority:
      name: Medium
    labels: []
task_template:
  1j5:
    issuetype:
      id: '10401'
    customfield_11568:
    - value: 动态视觉感知
    customfield_10200:
    - value: ES39_ZXD1.1_T1
    priority:
      name: Medium
    labels: []
    customfield_10655: '2025-03-15'
    project:
      id: 10948
    summary: zpd_es39_20250107_010621-动态障碍物-夜晚&晴天&高速,快速路-/VA/BackViewObstacles2dDet
    description: 
      数据回灌感知测试-zpd_es39_20250107_010621-动态障碍物-夜晚&amp;晴天&amp;高速,快速路-/VA/BackViewObstacles2dDet-异常记录及状态跟踪请见相关Confluence
      pages.
    assignee:
      name: lisen04
  2j5:
    issuetype:
      id: '10401'
    customfield_11568:
    - value: 感知
    customfield_10200:
    - value: 飞凡ES37智驾适配_T1
    priority:
      name: Low
    labels: []
    customfield_10655: '2024-08-11'
    project:
      id: 10948
    summary: AD_4.0.0.RC12
    description: 数据回灌感知测试-AD_4.0.0.RC12
    assignee:
      name: buyujun
token: NzkyMjEyNzA0NDU1Otp1O42u5nh9Kh0FGkED7RU5pCcZ
