# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReplayToolkit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_replay_toolkit(object):
    def setupUi(self, replay_toolkit):
        replay_toolkit.setObjectName("replay_toolkit")
        replay_toolkit.resize(1253, 797)
        self.centralwidget = QtWidgets.QWidget(replay_toolkit)
        self.centralwidget.setObjectName("centralwidget")
        self.toolkit_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.toolkit_tab.setGeometry(QtCore.QRect(0, 0, 1251, 751))
        self.toolkit_tab.setObjectName("toolkit_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.toolkit_tab.addTab(self.tab, "")
        self.bug_tab = QtWidgets.QWidget()
        self.bug_tab.setObjectName("bug_tab")
        self.label_13 = QtWidgets.QLabel(self.bug_tab)
        self.label_13.setGeometry(QtCore.QRect(590, 10, 541, 21))
        self.label_13.setObjectName("label_13")
        self.bug_table = QtWidgets.QTableWidget(self.bug_tab)
        self.bug_table.setGeometry(QtCore.QRect(10, 40, 1231, 671))
        self.bug_table.setObjectName("bug_table")
        self.bug_table.setColumnCount(0)
        self.bug_table.setRowCount(0)
        self.browse_bug = QtWidgets.QPushButton(self.bug_tab)
        self.browse_bug.setGeometry(QtCore.QRect(480, 10, 89, 25))
        self.browse_bug.setObjectName("browse_bug")
        self.bug_path = QtWidgets.QLineEdit(self.bug_tab)
        self.bug_path.setGeometry(QtCore.QRect(10, 10, 461, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bug_path.setFont(font)
        self.bug_path.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bug_path.setObjectName("bug_path")
        self.save_bug = QtWidgets.QPushButton(self.bug_tab)
        self.save_bug.setGeometry(QtCore.QRect(1138, 10, 101, 25))
        self.save_bug.setObjectName("save_bug")
        self.toolkit_tab.addTab(self.bug_tab, "")
        replay_toolkit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(replay_toolkit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1253, 22))
        self.menubar.setObjectName("menubar")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        replay_toolkit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(replay_toolkit)
        self.statusbar.setObjectName("statusbar")
        replay_toolkit.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuConfig.menuAction())

        self.retranslateUi(replay_toolkit)
        self.toolkit_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(replay_toolkit)

    def retranslateUi(self, replay_toolkit):
        _translate = QtCore.QCoreApplication.translate
        replay_toolkit.setWindowTitle(_translate("replay_toolkit", "ReplayToolkit"))
        self.toolkit_tab.setTabText(self.toolkit_tab.indexOf(self.tab), _translate("replay_toolkit", "TBD"))
        self.label_13.setText(_translate("replay_toolkit", "双击“场景编号”打开数据文件，双击“报告编号”打开报告文件，关闭前先点Save"))
        self.browse_bug.setText(_translate("replay_toolkit", "Browse"))
        self.save_bug.setText(_translate("replay_toolkit", "Save"))
        self.toolkit_tab.setTabText(self.toolkit_tab.indexOf(self.bug_tab), _translate("replay_toolkit", "BugViewer"))
        self.menuConfig.setTitle(_translate("replay_toolkit", "Config"))
