# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_inherent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_inherent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63\x61mera_inherent.proto\"o\n\rDistortCoeffs\x12\n\n\x02k1\x18\x01 \x01(\x01\x12\n\n\x02k2\x18\x02 \x01(\x01\x12\n\n\x02p1\x18\x05 \x01(\x01\x12\n\n\x02p2\x18\x06 \x01(\x01\x12\n\n\x02k3\x18\x03 \x01(\x01\x12\n\n\x02k4\x18\x04 \x01(\x01\x12\n\n\x02k5\x18\x07 \x01(\x01\x12\n\n\x02k6\x18\x08 \x01(\x01\">\n\x0c\x43\x61meraMatrix\x12\n\n\x02\x66x\x18\x01 \x01(\x01\x12\n\n\x02\x66y\x18\x02 \x01(\x01\x12\n\n\x02\x63x\x18\x03 \x01(\x01\x12\n\n\x02\x63y\x18\x04 \x01(\x01\"\xb2\x01\n\nIntrinsics\x12\x18\n\x10\x63\x61libration_time\x18\x01 \x01(\t\x12&\n\x0e\x64istort_coeffs\x18\x02 \x01(\x0b\x32\x0e.DistortCoeffs\x12$\n\rcamera_matrix\x18\x03 \x01(\x0b\x32\r.CameraMatrix\x12\x11\n\tserial_no\x18\x04 \x01(\t\x12\x1c\n\x14\x63\x61libration_engineer\x18\x05 \x01(\t\x12\x0b\n\x03rms\x18\x06 \x01(\x01\"\xab\x01\n\x0c\x43\x61meraConfig\x12\x1f\n\nintrinsics\x18\x01 \x01(\x0b\x32\x0b.Intrinsics\x12\x0f\n\x07max_fps\x18\x02 \x01(\x05\x12\"\n\x1amid_row_time_since_trigger\x18\x03 \x01(\x01\x12\x1b\n\x13rolling_elapse_time\x18\x04 \x01(\x01\x12\x15\n\rcamera_vendor\x18\x05 \x01(\t\x12\x11\n\tserial_no\x18\x06 \x01(\tb\x06proto3'
)




_DISTORTCOEFFS = _descriptor.Descriptor(
  name='DistortCoeffs',
  full_name='DistortCoeffs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='k1', full_name='DistortCoeffs.k1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k2', full_name='DistortCoeffs.k2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p1', full_name='DistortCoeffs.p1', index=2,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p2', full_name='DistortCoeffs.p2', index=3,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k3', full_name='DistortCoeffs.k3', index=4,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k4', full_name='DistortCoeffs.k4', index=5,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k5', full_name='DistortCoeffs.k5', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k6', full_name='DistortCoeffs.k6', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=136,
)


_CAMERAMATRIX = _descriptor.Descriptor(
  name='CameraMatrix',
  full_name='CameraMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fx', full_name='CameraMatrix.fx', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fy', full_name='CameraMatrix.fy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cx', full_name='CameraMatrix.cx', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cy', full_name='CameraMatrix.cy', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=200,
)


_INTRINSICS = _descriptor.Descriptor(
  name='Intrinsics',
  full_name='Intrinsics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibration_time', full_name='Intrinsics.calibration_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distort_coeffs', full_name='Intrinsics.distort_coeffs', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_matrix', full_name='Intrinsics.camera_matrix', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial_no', full_name='Intrinsics.serial_no', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calibration_engineer', full_name='Intrinsics.calibration_engineer', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rms', full_name='Intrinsics.rms', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=381,
)


_CAMERACONFIG = _descriptor.Descriptor(
  name='CameraConfig',
  full_name='CameraConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='intrinsics', full_name='CameraConfig.intrinsics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_fps', full_name='CameraConfig.max_fps', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mid_row_time_since_trigger', full_name='CameraConfig.mid_row_time_since_trigger', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rolling_elapse_time', full_name='CameraConfig.rolling_elapse_time', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_vendor', full_name='CameraConfig.camera_vendor', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial_no', full_name='CameraConfig.serial_no', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=555,
)

_INTRINSICS.fields_by_name['distort_coeffs'].message_type = _DISTORTCOEFFS
_INTRINSICS.fields_by_name['camera_matrix'].message_type = _CAMERAMATRIX
_CAMERACONFIG.fields_by_name['intrinsics'].message_type = _INTRINSICS
DESCRIPTOR.message_types_by_name['DistortCoeffs'] = _DISTORTCOEFFS
DESCRIPTOR.message_types_by_name['CameraMatrix'] = _CAMERAMATRIX
DESCRIPTOR.message_types_by_name['Intrinsics'] = _INTRINSICS
DESCRIPTOR.message_types_by_name['CameraConfig'] = _CAMERACONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DistortCoeffs = _reflection.GeneratedProtocolMessageType('DistortCoeffs', (_message.Message,), {
  'DESCRIPTOR' : _DISTORTCOEFFS,
  '__module__' : 'camera_inherent_pb2'
  # @@protoc_insertion_point(class_scope:DistortCoeffs)
  })
_sym_db.RegisterMessage(DistortCoeffs)

CameraMatrix = _reflection.GeneratedProtocolMessageType('CameraMatrix', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAMATRIX,
  '__module__' : 'camera_inherent_pb2'
  # @@protoc_insertion_point(class_scope:CameraMatrix)
  })
_sym_db.RegisterMessage(CameraMatrix)

Intrinsics = _reflection.GeneratedProtocolMessageType('Intrinsics', (_message.Message,), {
  'DESCRIPTOR' : _INTRINSICS,
  '__module__' : 'camera_inherent_pb2'
  # @@protoc_insertion_point(class_scope:Intrinsics)
  })
_sym_db.RegisterMessage(Intrinsics)

CameraConfig = _reflection.GeneratedProtocolMessageType('CameraConfig', (_message.Message,), {
  'DESCRIPTOR' : _CAMERACONFIG,
  '__module__' : 'camera_inherent_pb2'
  # @@protoc_insertion_point(class_scope:CameraConfig)
  })
_sym_db.RegisterMessage(CameraConfig)


# @@protoc_insertion_point(module_scope)
