Replay02:
  master:
    ip: 172.31.131.253
    username: zhangliwei01
    password: Pass1234
    py_path: /home/zhangliwei01/ZONE/PythonProject/Replay-Autotest-at-Home
  ReplayClient:
    ip: 172.31.131.222
    username: vcar
    password: 123456
    py_path: /home/vcar/work/pythonProject/Replay-Autotest-at-Home
    ECU_product_preferred: ES37