Replay04:
  Master:
    ip: localhost
    username: appuser
    password: Zone,456
    py_path: /home/appuser/PycharmProjects/Replay-Autotest-at-Home
    sys_interpreter: /home/appuser/PycharmProjects/Replay-Autotest-at-Home/.venv/bin/python3
    sil_pkg_path: /home/appuser/aeb_replay/sil
    ros_docker_path: /home/appuser/aeb_replay/docker_rolling/docker_rolling_hil.sh
  ReplayClient:
    ip: 10.192.68.71
    username: vcar
    password: 123456
    py_path: /home/vcar/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
Replay03:
  Master:
    ip: localhost
    username: hp
    password: admin
    py_path: /home/hp/Replay-Autotest-at-Home
    sys_interpreter: /home/hp/ZONE/PythonProject/base_interpreter/.venv/bin/python3
    ros_docker_path: /home/hp/docker_rolling.sh
  ReplayClient:
    ip: 10.192.68.115
    username: vcar
    password: 123456
    py_path: /home/vcar/work/pythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
Replay02:
  Master:
    ip: 172.31.1.253
    username: zhangliwei01
    password: Pass1234
    py_path: /home/zhangliwei01/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
    sil_pkg_path: /home/zhangliwei01/ZONE/sil_pkg/sil
    ros_docker_path: self
  ReplayClient:
    ip: 10.192.68.71
    username: vcar
    password: 123456
    py_path: /home/vcar/work/PythonProject
    sys_interpreter: /usr/bin/python3
Replay01:
  Master:
    ip: 172.31.1.253
    username: caobingqi
    password: Pass1234
    py_path: /home/caobingqi/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
    ros_docker_path: self
  ReplayClient:
    ip: 172.31.1.222
    username: vcar
    password: 123456
    py_path: /home/vcar/work/pythonproject/HIL_test_at_home/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
Replay00:
  Master:
    ip: localhost
    username: byj
    password: 123456
    py_path: /home/byj/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
    ros_docker_path: self
  ReplayClient:
    ip: 10.192.68.71
    username: vcar
    password: 123456
    py_path: /home/vcar/work/PythonProject
    sys_interpreter: /usr/bin/python3
Replay0Z:
  Master:
    ip: 10.192.68.71
    username: vcar
    password: 123456
    py_path: /home/vcar/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
    ros_docker_path: /home/vcar/docker_rolling_hil.sh