Replay02:
  master:
    ip: 172.31.131.253
    username: zhangliwei01
    password: Pass1234
    py_path: /home/zhangliwei01/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
  ReplayClient:
    ip: 172.31.131.222
    username: vcar
    password: 123456
    py_path: /home/vcar/work/pythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
    ECU_product_preferred: ES37
Replay01:
  master:
    ip: 172.31.131.253
    username: caobingqi
    password: Pass1234
    py_path: /home/caobingqi/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
  ReplayClient:
    ip: 172.31.131.222
    username: vcar
    password: 123456
    py_path: /home/vcar/work/pythonproject/HIL_test_at_home/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3
    ECU_product_preferred: 1J5
Replay00:
  master:
    ip: localhost
    username: byj
    password: 123456
    py_path: /home/byj/ZONE/PythonProject/Replay-Autotest-at-Home
    sys_interpreter: /usr/bin/python3